--- #YAML:1.0
name:               Imager-Screenshot
version:            0.011
abstract:           Screen/Window capture to Imager images
author:
    - Tony Cook <tonyc@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    Imager:               0.69
build_requires:
    ExtUtils::MakeMaker:  0
    Imager:               0.69
    Test::More:           0.47
requires:
    Imager:  0.69
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Imager-Screenshot
    homepage:    http://imager.perl.org/
    repository:  git://git.imager.perl.org/imager-screenshot.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     1
