--- #YAML:1.0
name:                Imager-Screenshot
version:             0.004
abstract:            Screen/Window capture to Imager images
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Imager:                        0.54
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Tony Cook <tonyc@cpan.org>
